'''Generate Empty Gold

This script creates an initial gold `.py` file for parsing a drawing procedure.

When running this script, it will prompt the user for a username and a procedure index.
The username will be written inside the gold file.
If you enter the username `Bond` and the procedure number `7`, the gold file
will be named: `Bond_gold_007.py`.

The gold file will contain the drawing procedure instructions,
and everything else needed for running the file (as a script).
The user can fill in the necessary code under each step of the instructions.

When running the gold file, the gold image will be plotted,
together with the image generated by the code written by the user.
The difference between the two images will also be plotted.
'''

import os.path

from utils.reading_tasks import read_task

def main():

  # read the task from jsonl files
  user_name = input("Please enter a username: ")
  task_index = int(input("Please provide the task index: "))
  task_dict = read_task(task_index)

  # use template to create file
  with open('../gold/template.txt', 'r') as file:
    template = file.read().split('\n')

  # create new file and write to it
  file_name = f'{user_name}_gold_{task_index:0>3}'
  file_path = '../gold/' + file_name + '.py'
  if os.path.exists(file_path):
    print(f'file {file_name} already exists')
  else:
    print(f'creating file {file_name}')
    with open(file_path, 'w+') as file_id:
      file_id.write(f'# Created by by {user_name}\n\n')
      file_id.write('\n'.join(template[:3]))
      file_id.write(f'\ntask_index = {task_index}\n')
      file_id.write('\n'.join(template[4:9]))
      file_id.write(f"\n{task_dict['description']}\n\n")
      file_id.write(task_dict['instructions'])
      file_id.write('\n'.join(template[12:]))

if __name__ == "__main__":
  main()