# Auto-generated abstraction layer — do not edit manually.
# Generated by validate_dsl_candidates.py

from typing import List, Tuple, Optional
import cadquery as cq


# pattern: cq.Workplane -> circle -> circle -> extrude
def tube(outer_radius: float, inner_radius: float, height: float) -> cq.Workplane:
    """Create a hollow cylinder (tube) along the Z axis."""
    return (
        cq.Workplane("XY")
        .circle(outer_radius)
        .circle(inner_radius)
        .extrude(height)
    )


# pattern: faces -> workplane -> pushPoints -> hole
def holesOnFace(
    obj: cq.Workplane,
    face_selector: str,
    points: List[Tuple[float, float]],
    diameter: float,
    depth: Optional[float] = None
) -> cq.Workplane:
    """Create multiple holes on a specified face at the given points."""
    return obj.faces(face_selector).workplane().pushPoints(points).hole(diameter, depth)


# pattern: faces -> workplane -> rect -> cutThruAll
def rectangularThroughHole(wp: cq.Workplane, width: float, height: float, face_selector: str = ">Z", centered: bool = True) -> cq.Workplane:
    """Cuts a rectangular through-hole into the specified face of a workplane."""
    return (
        wp.faces(face_selector)
        .workplane()
        .rect(width, height, centered=centered)
        .cutThruAll()
    )


# pattern: faces -> workplane -> center -> circle -> cutThruAll
def centeredThroughHole(
    obj: cq.Workplane,
    radius: float,
    x_offset: float = 0.0,
    y_offset: float = 0.0,
    face_selector: str = ">Z"
) -> cq.Workplane:
    """Create a through-hole of the given radius at the specified center offset on a selected face."""
    return obj.faces(face_selector).workplane().center(x_offset, y_offset).circle(radius).cutThruAll()


# pattern: extrude -> faces -> workplane -> pushPoints -> hole
def extrude_with_holes(
    wp: cq.Workplane,
    extrude_dist: float,
    face_selector: str,
    points: List[Tuple[float, float]],
    diameter: float,
    depth: Optional[float] = None
) -> cq.Workplane:
    """Extrude a sketch, select a face, and drill holes at the specified points."""
    return (
        wp.extrude(extrude_dist)
        .faces(face_selector)
        .workplane()
        .pushPoints(points)
        .hole(diameter, depth)
    )


# pattern: rect -> extrude -> faces -> workplane -> rect -> cutThruAll
def rectangular_frame(length: float, width: float, height: float, hole_length: float, hole_width: float) -> cq.Workplane:
    """Create a rectangular block with a rectangular through-hole."""
    return (
        cq.Workplane("XY")
        .rect(length, width)
        .extrude(height)
        .faces(">Z")
        .workplane()
        .rect(hole_length, hole_width)
        .cutThruAll()
    )


# pattern: cq.Workplane -> pushPoints -> circle -> extrude
def extrudeCircles(points: list[tuple[float, float]], radius: float, depth: float, workplane: str = "XY") -> cq.Workplane:
    """Extrude multiple circles at specified points on a workplane."""
    return cq.Workplane(workplane).pushPoints(points).circle(radius).extrude(depth)


# pattern: threePointArc -> lineTo -> threePointArc -> close
def slot(start: tuple[float, float], end: tuple[float, float], radius: float, wp: cq.Workplane = None) -> cq.Workplane:
    """Create a 2D slot or obround profile between two points with a given radius."""
    if wp is None:
        wp = cq.Workplane("XY")

    x1, y1 = start
    x2, y2 = end

    dx = x2 - x1
    dy = y2 - y1
    length = (dx**2 + dy**2)**0.5

    if length == 0:
        return wp.moveTo(x1, y1).circle(radius)

    nx = -dy / length
    ny = dx / length
    ux = dx / length
    uy = dy / length

    p1 = (x1 + radius * nx, y1 + radius * ny)
    p2 = (x2 + radius * nx, y2 + radius * ny)
    arc1_mid = (x2 + radius * ux, y2 + radius * uy)
    p3 = (x2 - radius * nx, y2 - radius * ny)
    p4 = (x1 - radius * nx, y1 - radius * ny)
    arc2_mid = (x1 - radius * ux, y1 - radius * uy)

    return (
        wp.moveTo(*p1)
        .lineTo(*p2)
        .threePointArc(arc1_mid, p3)
        .lineTo(*p4)
        .threePointArc(arc2_mid, p1)
        .close()
    )


